export { pluginRegistry } from "./registry.js";
export type { PluginHandler, PluginContext, PluginResult } from "./types.js";
export { shoppingPlugin } from "./shopping.js";
export { fitnessPlugin } from "./fitness.js";
export { nutritionPlugin } from "./nutrition.js";
export { plantPetPlugin } from "./plant-pet.js";
export { styleMatchPlugin } from "./style-match.js";
export { hagglePlugin } from "./haggle.js";
export { roomDesignPlugin } from "./room-design.js";
export { objectHistoryPlugin } from "./object-history.js";
export { comparisonPlugin } from "./comparison.js";
